<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MohamedAli" failures="1" tests="1" name="pipelineTest3.pipelineTest3.Runner3" time="16.643" errors="0" timestamp="2023-02-28T08:42:06 CET" skipped="0">
  <testcase classname="pipelineTest3.pipelineTest3.Runner3" name="runScenario" time="16.643">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at pipelineTest3.pipelineTest3.LoginPipeline3Steps.a_warning_message_is_displayed(LoginPipeline3Steps.java:40)
at âœ½.A warning message is displayed(file:///C:/Users/moham/eclipse-workspace/pipelineTest3/src/test/resources/features/loginTest3.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- pipelineTest3.pipelineTest3.Runner3 -->
